x_angular_deg: 2
y_angular_deg: 2
front_aperture: 1
sigma: 7.0
paths:
  fits: "/example/data/fits6"
  stars: "/example/data/stars/tycho_catalog_export.csv"
grid:
  mode: "polar"
  angle_steps: 1
  speed_steps: 1
  max_speed_arcsec: 0.3
  min_speed: 0.3
wcs:
  image_shape: [512, 512]
  fov_x_deg: 2.0
  fov_y_deg: 2.0
  ra_center_deg: 90.0
  dec_center_deg: 0.0